## Setup

```{r}
#| label: load-and-clean

library(tidyverse)
library(knitr) 
library(ggfortify)
library(gplots)

load("./data/yeast.RData")

str(y)  # Check the structure of the dataset
summary(y)  # Summary statistics

cor(y$Location_Center_X, y$AreaShape_Center_X) # 100% correlated
cor(y$Location_Center_Y, y$AreaShape_Center_Y) # 100% correlated

yeast <- y |> select(!c(Location_Center_X, Location_Center_Y))

data_scaled <- data.frame(scale(y[, sapply(y, is.numeric)]))
```


## Feature EDA

```{r}
#| label: feature-anova

# significant

yeast |> ggplot(aes(x = AreaShape_Area, y = strain)) + geom_boxplot()
summary(aov(AreaShape_Area ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_BoundingBoxArea, y = strain)) + geom_boxplot()
summary(aov(AreaShape_BoundingBoxArea ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_Compactness, y = strain)) + geom_boxplot()
summary(aov(AreaShape_Compactness ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_ConvexArea, y = strain)) + geom_boxplot()
summary(aov(AreaShape_ConvexArea ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_Eccentricity, y = strain)) + geom_boxplot()
summary(aov(AreaShape_Eccentricity ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_EquivalentDiameter, y = strain)) + geom_boxplot()
summary(aov(AreaShape_EquivalentDiameter ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_Extent, y = strain)) + geom_boxplot()
summary(aov(AreaShape_Extent ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_FormFactor, y = strain)) + geom_boxplot()
summary(aov(AreaShape_FormFactor ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_MajorAxisLength, y = strain)) + geom_boxplot()
summary(aov(AreaShape_MajorAxisLength ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_MaxFeretDiameter, y = strain)) + geom_boxplot()
summary(aov(AreaShape_MaxFeretDiameter ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_MaximumRadius, y = strain)) + geom_boxplot()
summary(aov(AreaShape_MaximumRadius ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_MeanRadius, y = strain)) + geom_boxplot()
summary(aov(AreaShape_MeanRadius ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_MedianRadius, y = strain)) + geom_boxplot()
summary(aov(AreaShape_MedianRadius ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_MinFeretDiameter, y = strain)) + geom_boxplot()
summary(aov(AreaShape_MinFeretDiameter ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_MinorAxisLength, y = strain)) + geom_boxplot()
summary(aov(AreaShape_MinorAxisLength ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_Orientation, y = strain)) + geom_boxplot()
summary(aov(AreaShape_Orientation ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_Perimeter, y = strain)) + geom_boxplot()
summary(aov(AreaShape_Perimeter ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_Solidity, y = strain)) + geom_boxplot()
summary(aov(AreaShape_Solidity ~ strain, data = yeast))

# not significant

yeast |> ggplot(aes(x = AreaShape_BoundingBoxMaximum_X, y = strain)) + geom_boxplot()
summary(aov(AreaShape_BoundingBoxMaximum_X ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_BoundingBoxMaximum_Y, y = strain)) + geom_boxplot()
summary(aov(AreaShape_BoundingBoxMaximum_Y ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_BoundingBoxMinimum_X, y = strain)) + geom_boxplot()
summary(aov(AreaShape_BoundingBoxMinimum_X ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_BoundingBoxMinimum_Y, y = strain)) + geom_boxplot()
summary(aov(AreaShape_BoundingBoxMinimum_Y ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_Center_X, y = strain)) + geom_boxplot()
summary(aov(AreaShape_Center_X ~ strain, data = yeast))

yeast |> ggplot(aes(x = AreaShape_Center_Y, y = strain)) + geom_boxplot()
summary(aov(AreaShape_Center_Y ~ strain, data = yeast))

yeast |> ggplot(aes(x = nNN50, y = strain)) + geom_boxplot()
summary(aov(nNN50 ~ strain, data = yeast))

```

```{r}
drop <- c("AreaShape_BoundingBoxMaximum_X", "AreaShape_BoundingBoxMaximum_Y", "AreaShape_BoundingBoxMinimum_X", "AreaShape_BoundingBoxMinimum_Y", "AreaShape_Center_X", "AreaShape_Center_Y", "nNN50")

yeast <- yeast |> select(!(all_of(drop)))
data_scaled_new <- data.frame(scale(yeast[, sapply(yeast, is.numeric)]))

covariance <- cov(data_scaled_new)

covariance |> kable(digits = 2)

# highly correlated variables
# area, boundingboxarea, equivalentdiameter, majoraxislength, maxferetdiameter, maximumradius, meanradius, medianradius, minferetdiameter, minoraxislength, perimeter
# compactness, formfactor, solidity
# eccentricity
# extent
# orientation

# take based off f-value in ANOVA (explains most difference between groups): perimeter, formfactor, eccentricity, extent, orientation
```

```{r}
#| label: new-pca-analysis

pca <- prcomp(data_scaled_new, center = TRUE, scale. = TRUE)
sum <- summary(pca)
data.frame(sum$importance) |> select(PC1, PC2) |> kable()

var_explained <- pca$sdev^2 / sum(pca$sdev^2)
# sum(var_explained[1:2])

ggplot(data = data.frame(PC = 1:length(var_explained), 
                         Variance = var_explained),
       aes(x = PC, y = Variance)) +
  geom_line() +
  geom_point(size = 4) +
  geom_text(aes(label = round(Variance, 2)), vjust = -0.5) +
  scale_x_continuous(breaks = 1:length(var_explained)) +
  xlab("Principal Component") +
  ylab("Proportion of Variance Explained") +
  ggtitle("Scree Plot") +
  theme_minimal()

loadings <- abs(pca$rotation[, 1:2])  # Focus on PC1-2

loadings_mod <- data.frame(loadings) |> mutate(weighted = PC1 * var_explained[1] +
                                     PC2 * var_explained[2])

loadings_mod_final <- loadings_mod |> select(weighted) |> arrange(desc(weighted)) 


loadings_mod_final |> kable(digits = 3)
```


```{r}
#| label: new-cluster-analysis

# temp <- yeast |> select(AreaShape_Perimeter, AreaShape_FormFactor, AreaShape_Eccentricity, AreaShape_Extent, AreaShape_Orientation, strain, uniqueWell, uniqueImage, uniqueID) |> mutate(across(where(is.numeric), scale))
# 
# temp_full <- temp |> group_by(uniqueImage) |>
#    summarise(across(where(is.numeric), ~median(., na.rm = TRUE))) |>
#    column_to_rownames(var = "uniqueImage")

temp <- yeast |> select(AreaShape_MeanRadius, AreaShape_FormFactor, AreaShape_Eccentricity, AreaShape_Extent, AreaShape_Orientation, strain, uniqueWell, uniqueImage, uniqueID) |> mutate(across(where(is.numeric), scale))

temp_full <- temp |> group_by(uniqueImage) |>
   summarise(across(where(is.numeric), ~median(., na.rm = TRUE))) |>
   column_to_rownames(var = "uniqueImage")

# temp <- yeast |> select(AreaShape_Perimeter, AreaShape_FormFactor, AreaShape_Eccentricity, AreaShape_Extent, strain, uniqueWell, uniqueImage, uniqueID) |> mutate(across(where(is.numeric), scale))
# 
# temp_orientation <- yeast |> select(AreaShape_Orientation, strain, uniqueWell, uniqueImage, uniqueID) |> mutate(across(where(is.numeric), scale))
# 
# temp_sum <- temp |> group_by(uniqueImage) |>
#   summarise(across(where(is.numeric), ~median(., na.rm = TRUE))) |>
#   mutate(uniqueWell = substring(uniqueImage, 0, 4))
# 
# temp_orientation_sum <- temp_orientation |> group_by(uniqueWell) |>
#   summarise(across(where(is.numeric), ~median(., na.rm = TRUE)))
# 
# temp_full <- left_join(temp_sum, temp_orientation_sum, by = c("uniqueWell" = "uniqueWell")) |>
#   column_to_rownames(var = "uniqueImage") |>
#   select(!uniqueWell)

dist_matrix <- dist(temp_full)

hc_result <- hclust(dist_matrix, method = "average")
plot(hc_result, main = "Hierarchical Clustering on Important Features", xlab = "", sub = "")

heatmap.2(as.matrix(temp_full),scale="none",trace="none",
          cexCol=1)
```

```{r}
#| label: C-03-well-examination

temp_filtered <- temp |> filter(uniqueWell == "C-03")
colnames(temp_filtered)

temp_filtered |> ggplot(aes(x = AreaShape_Perimeter, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Perimeter ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_FormFactor, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_FormFactor ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Eccentricity, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Eccentricity ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Extent, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Extent ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Orientation, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Orientation ~ uniqueImage, data = temp_filtered))
```

```{r}
#| label: C-04-well-examination

temp_filtered <- temp |> filter(uniqueWell == "C-04")
colnames(temp_filtered)

temp_filtered |> ggplot(aes(x = AreaShape_Perimeter, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Perimeter ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_FormFactor, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_FormFactor ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Eccentricity, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Eccentricity ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Extent, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Extent ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Orientation, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Orientation ~ uniqueImage, data = temp_filtered))
```

```{r}
#| label: D-03-well-examination

temp_filtered <- temp |> filter(uniqueWell == "D-03")
colnames(temp_filtered)

temp_filtered |> ggplot(aes(x = AreaShape_Perimeter, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Perimeter ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_FormFactor, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_FormFactor ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Eccentricity, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Eccentricity ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Extent, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Extent ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Orientation, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Orientation ~ uniqueImage, data = temp_filtered))
```

```{r}
#| label: D-04-well-examination

temp_filtered <- temp |> filter(uniqueWell == "D-04")
colnames(temp_filtered)

temp_filtered |> ggplot(aes(x = AreaShape_Perimeter, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Perimeter ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_FormFactor, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_FormFactor ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Eccentricity, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Eccentricity ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Extent, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Extent ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Orientation, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Orientation ~ uniqueImage, data = temp_filtered))
```

```{r}
#| label: E-03-well-examination

temp_filtered <- temp |> filter(uniqueWell == "E-03")
colnames(temp_filtered)

temp_filtered |> ggplot(aes(x = AreaShape_Perimeter, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Perimeter ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_FormFactor, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_FormFactor ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Eccentricity, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Eccentricity ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Extent, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Extent ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Orientation, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Orientation ~ uniqueImage, data = temp_filtered))
```

```{r}
#| label: E-04-well-examination

temp_filtered <- temp |> filter(uniqueWell == "E-04")
colnames(temp_filtered)

temp_filtered |> ggplot(aes(x = AreaShape_Perimeter, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Perimeter ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_FormFactor, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_FormFactor ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Eccentricity, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Eccentricity ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Extent, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Extent ~ uniqueImage, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Orientation, y = uniqueImage)) + geom_boxplot()
summary(aov(AreaShape_Orientation ~ uniqueImage, data = temp_filtered))
```

```{r}
#| label: C-strain-examination

temp_filtered <- temp |> filter(strain == "C")
colnames(temp_filtered)

temp_filtered |> ggplot(aes(x = AreaShape_Perimeter, y = uniqueWell)) + geom_boxplot()
summary(aov(AreaShape_Perimeter ~ uniqueWell, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_FormFactor, y = uniqueWell)) + geom_boxplot()
summary(aov(AreaShape_FormFactor ~ uniqueWell, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Eccentricity, y = uniqueWell)) + geom_boxplot()
summary(aov(AreaShape_Eccentricity ~ uniqueWell, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Extent, y = uniqueWell)) + geom_boxplot()
summary(aov(AreaShape_Extent ~ uniqueWell, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Orientation, y = uniqueWell)) + geom_boxplot()
summary(aov(AreaShape_Orientation ~ uniqueWell, data = temp_filtered))
```

```{r}
#| label: D-strain-examination

temp_filtered <- temp |> filter(strain == "D")
colnames(temp_filtered)

temp_filtered |> ggplot(aes(x = AreaShape_Perimeter, y = uniqueWell)) + geom_boxplot()
summary(aov(AreaShape_Perimeter ~ uniqueWell, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_FormFactor, y = uniqueWell)) + geom_boxplot()
summary(aov(AreaShape_FormFactor ~ uniqueWell, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Eccentricity, y = uniqueWell)) + geom_boxplot()
summary(aov(AreaShape_Eccentricity ~ uniqueWell, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Extent, y = uniqueWell)) + geom_boxplot()
summary(aov(AreaShape_Extent ~ uniqueWell, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Orientation, y = uniqueWell)) + geom_boxplot()
summary(aov(AreaShape_Orientation ~ uniqueWell, data = temp_filtered))
```

```{r}
#| label: E-strain-examination

temp_filtered <- temp |> filter(strain == "E")
colnames(temp_filtered)

temp_filtered |> ggplot(aes(x = AreaShape_Perimeter, y = uniqueWell)) + geom_boxplot()
summary(aov(AreaShape_Perimeter ~ uniqueWell, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_FormFactor, y = uniqueWell)) + geom_boxplot()
summary(aov(AreaShape_FormFactor ~ uniqueWell, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Eccentricity, y = uniqueWell)) + geom_boxplot()
summary(aov(AreaShape_Eccentricity ~ uniqueWell, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Extent, y = uniqueWell)) + geom_boxplot()
summary(aov(AreaShape_Extent ~ uniqueWell, data = temp_filtered))

temp_filtered |> ggplot(aes(x = AreaShape_Orientation, y = uniqueWell)) + geom_boxplot()
summary(aov(AreaShape_Orientation ~ uniqueWell, data = temp_filtered))
```